[package]
name = "logind-zbus"
version = "0.4.0"
license = "MPL-2.0"
authors = ["Luke D Jones <luke@ljones.dev>"]
edition = "2018"
readme = "README.md"
repository = "https://gitlab.com/flukejones/logind-zbus"
homepage = "https://gitlab.com/flukejones/logind-zbus"
documentation = "https://docs.rs/logind-zbus"
description = "A dbus client (using zbus) for logind"
keywords = ["systemd", "logind", "zbus"]
categories = ["os::unix-apis"]

[features]
azync = []

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
zbus = "^2.0.0-beta.3"
zbus_macros = "^2.0.0-beta.3"
zvariant = "^2.6"
zvariant_derive = "^2.6"